
version: 2

updates:

  # maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "./"
    schedule:
      interval: "monthly"


  # maintain dependencies for npm
  - package-ecosystem: npm
    directory: "./frontend"
    schedule:
      interval: "monthly"

  # maintain dependencies for fastapi
  - package-ecosystem: pip
    directory: "./api"
    schedule:
      interval: "monthly"
