export const SET_USER_CREDENTIALS = "SET_USER_CREDENTIALS";
export const SET_PRIVATE_CHANNEL = "SET_PRIVATE_CHANNEL";
export const SET_SINGLE_VIDEO = "SET_SINGLE_VIDEO";
export const SET_CHANNEL_VIDEO_LIST = "SET_CHANNEL_VIDEO_LIST";
export const ADD_VIDEO_TO_CHANNEL = "ADD_VIDEO_TO_CHANNEL";
